title: Yaseer Arafat
description: A portfolio and blog by emonarafat
url: "https://emonarafat.github.io"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

social:
  github: emonarafat
  twitter: emontwitts
  linkedin: yaseerarafat
  
breadcrumbs: true  # disabled by default

markdown: kramdown

# google_analytics: "UA-XXXXXX-X"

# Exclude these files/folders from the build
exclude:
  - node_modules
  - README.md
