title: Yaseer Arafat
description: A portfolio and blog by emonarafat
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

author:
  name: Yaseer Arafat
  email: yaseer.arafat@live.com

social:
  github: emonarafat
  twitter: emontwitts
  linkedin: yaseerarafat
  
breadcrumbs: true  # disabled by default

markdown: kramdown

# google_analytics: "UA-XXXXXX-X"

# Exclude these files/folders from the build
exclude:
  - node_modules

# Example navigation (if supported by your theme)
nav:
   - Home: /
   - Mastering CQRS with MediatR: /CQRS-MeditR-Demo
   - Mastering CancellationToken: /Mastering_CancellationToken
