title: My Awesome Site
description: A portfolio and blog by emonarafat
theme: jekyll-theme-architect

author:
  name: Yaseer Arafat
  email: yaseer.arafat@live.com

social:
  github: emonarafat
  twitter: emontwitts
  linkedin: yaseerarafat

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown

# google_analytics: "UA-XXXXXX-X"

# Exclude these files/folders from the build
exclude:
  - node_modules

# Example navigation (if supported by your theme)
# nav:
#   - Home: /
#   - Blog: /blog/
#   - About: /about/
