title: Yaseer Arafat
description: A portfolio and blog by emonarafat
remote_theme: pages-themes/primer@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

author:
  name: Yaseer Arafat
  email: yaseer.arafat@live.com

social:
  github: emonarafat
  twitter: emontwitts
  linkedin: yaseerarafat

plugins:
  - jekyll-feed
  - jekyll-seo-tag

markdown: kramdown

# google_analytics: "UA-XXXXXX-X"

# Exclude these files/folders from the build
exclude:
  - node_modules

# Example navigation (if supported by your theme)
nav:
   - Home: /
   - Mastering CQRS with MediatR: /CQRS-MeditR-Demo
   - Mastering CancellationToken: /Mastering_CancellationToken
